version: '3'

services:
  backend:
    container_name: django_react_backend
    build:
      context: ./backend
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    command: |
      bash -c "if [ ! -f manage.py ]; then
        django-admin startproject ${DJANGO_PROJECT_NAME} .;
      fi;
      python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - ${DJANGO_PORT}

  frontend:
    container_name: django_react_frontend
    build:
      context: ./frontend
      args:
        NODE_VERSION: ${NODE_VERSION}
    command: |
      bash -c "if [ ! -d ${REACT_PROJECT_NAME} ]; then
        npx create-react-app ${REACT_PROJECT_NAME};
      fi;
      cd ${REACT_PROJECT_NAME} && npm start"
    volumes:
      - ./frontend:/app
    ports:
      - ${REACT_PORT}
    depends_on:
      - backend
